<div id="orders_page" class="j-navigation-page j-control-container item">
    <?php $this->render('popup/edit-order') ?>

    <div class="page-header">
        <h1>
            Заказы
            <small>
                Здесь вы можете управлять своими заказами
            </small>
        </h1>
    </div>

    <div class="row">
        <div class="span12">

            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>№</th>
                        <th>Дата</th>
                        <th>Клиент</th>
                        <th>Цена</th>
                        <th>Статус</th>
                        <th>Доставка</th>
                        <th>Оплата</th>
                        <th>Действия</th>
                    </tr>
                </thead>
                <tbody class="t-orders-list j-button-group"
                       data-name="order-controls">
                    <tr>
                        <td>14</td>
                        <td>24.02.2012 20:00</td>
                        <td>Сергей Кононенко</td>
                        <td>1300</td>
                        <td>
                            <span class="label label-important">Новый</span>
                        </td>
                        <td>
                            <span class="label label-warning">Подготовка</span>
                        </td>
                        <td>
                            <span class="label label-important">Не оплачен</span>
                        </td>
                        <td>
                            <ul class="nav nav-list">
                                <li>
                                    <a class="j-button" href="#"
                                       data-action="edit">
                                        <i class="icon-edit"></i>
                                        Редактировать
                                    </a>
                                </li>
                            </ul>
                        </td>
                    </tr>
                </tbody>
            </table>

        </div>
    </div>
</div>