<form action="/api/" method="POST" target="support_frame"
      class="j-form j-popup form-horizontal hide"
      data-name="edit-recipe" data-record-type="recipe">

    <input type="hidden" name="method" value="recipe.edit" />
    <input type="hidden" name="format" value="frame-callback" />

    <div class="modal">
        <div class="modal-header">
            <h3 class="t-recipe-name">Марципан</h3>
        </div>

        <div class="modal-body">
            <div class="j-form-message alert alert-error hide"></div>

            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Вес</th>
                        <th>Форма</th>
                        <th>Цена</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1 кг.</td>
                        <td>Круг</td>
                        <td>1000 руб.</td>
                    </tr>
                    <tr>
                        <td>1 кг.</td>
                        <td>Квадрат</td>
                        <td>1000 руб.</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="modal-footer">
            <a class="j-popup-apply btn btn-primary">Сохранить</a>
            <a class="j-popup-close btn">Отмена</a>
        </div>
    </div>
    <div class="modal-backdrop"></div>
</form>