<form action="/api/" method="POST" target="support_frame"
      class="j-form j-popup form-horizontal hide"
      data-name="edit-order" data-record-type="order">

    <input type="hidden" name="method" value="recipe.edit" />
    <input type="hidden" name="format" value="frame-callback" />

    <div class="j-navigation modal">
        <div class="modal-header">
            <ul class="j-navigation-menu nav nav-pills">
                <li class="j-navigation-link" data-href="edit_order_common">
                    <a href="#">Общее</a>
                </li>
                <li class="j-navigation-link" data-href="edit_order_client">
                    <a href="#">Клиент</a>
                </li>
                <li class="j-navigation-link" data-href="edit_order_cake">
                    <a href="#">Торт</a>
                </li>
                <li class="j-navigation-link" data-href="edit_order_delivery">
                    <a href="#">Доставка</a>
                </li>
                <li class="j-navigation-link" data-href="edit_order_payment">
                    <a href="#">Оплата</a>
                </li>
            </ul>
        </div>

        <div class="modal-body">
            <div class="j-form-message alert alert-error hide"></div>

            <div class="carousel">
                <div class="carousel-inner">
                    <fieldset id="edit_order_common" class="j-navigation-page active item">

                        <div class="control-group">
                            <label class="control-label">Статус: </label>
                            <div class="controls">
                                <label class="radio">
                                    <input type="radio" name="status" checked />
                                    <span class="label label-important">Новый</span>
                                </label>
                                <label class="radio">
                                    <input type="radio" name="status" />
                                    <span class="label label-success">Подтвержден</span>
                                </label>
                                <label class="radio">
                                    <input type="radio" name="status" />
                                    <span class="label">Отклонен</span>
                                </label>
                            </div>
                        </div>

                    </fieldset>

                    <fieldset id="edit_order_client" class="j-navigation-page item">

                        <div class="control-group">
                            <label class="control-label">Имя: </label>
                            <div class="controls">
                                <input disabled type="text" value="Сергей Кононенко" />
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Телефон: </label>
                            <div class="controls">
                                <input disabled type="text" value="+7 (952) 232-90-25" />
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Email: </label>
                            <div class="controls">
                                <input disabled type="text" value="kononencheg@gmail.com" />
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Откуда: </label>
                            <div class="controls">
                                <select disabled>
                                    <option>Вконтакте</option>
                                </select>
                            </div>
                        </div>

                    </fieldset>
                    
                    <fieldset id="edit_order_cake" class="j-navigation-page item">

                        <div class="control-group">
                            <label class="control-label">Рецепт: </label>
                            <div class="controls">
                                <select disabled>
                                    <option>Марципан</option>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Форма: </label>
                            <div class="controls">
                                <select disabled>
                                    <option>Круглый</option>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Вес: </label>
                            <div class="controls">
                                <input disabled type="text" value="1.5" />
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Изображение: </label>
                            <div class="controls">
                                <input class="btn " type="button" value="Скачать" />
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Фото: </label>
                            <div class="controls">
                                <input class="btn" type="button" value="Скачать" />
                            </div>
                        </div>

                    </fieldset>
                    
                    <fieldset id="edit_order_delivery" class="j-navigation-page item">

                        <div class="control-group">
                            <label class="control-label">Адрес: </label>
                            <div class="controls">
                                <textarea disabled>ул. Наличная, д. 37, корп. 2</textarea>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Дата: </label>
                            <div class="controls">
                                <input disabled type="text" value="24.02.2012 20:00" />
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Статус: </label>
                            <div class="controls">
                                <label class="radio">
                                    <input type="radio" name="delivery_status" checked />
                                    <span class="label label-warning">Подготовка</span>
                                </label>
                                <label class="radio">
                                    <input type="radio" name="delivery_status" />
                                    <span class="label label-info">В доставке</span>
                                </label>
                                <label class="radio">
                                    <input type="radio" name="delivery_status" />
                                    <span class="label label-success">Доставлено</span>
                                </label>
                            </div>
                        </div>

                    </fieldset>

                    <fieldset id="edit_order_payment" class="j-navigation-page item">

                        <div class="control-group">
                            <label class="control-label">Тип: </label>
                            <div class="controls">
                                <select disabled>
                                    <option>Наличными</option>
                                </select>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">Статус: </label>
                            <div class="controls">
                                <label class="radio">
                                    <input type="radio" name="payment_status" checked />
                                    <span class="label label-important">Не оплачен</span>
                                </label>
                                <label class="radio">
                                    <input type="radio" name="payment_status" />
                                    <span class="label label-success">Оплачен</span>
                                </label>
                            </div>
                        </div>

                    </fieldset>
                </div>
            </div>

        </div>

        <div class="modal-footer">
            <a class="j-popup-close btn">Закрыть</a>
        </div>
    </div>
    <div class="modal-backdrop"></div>
</form>