<div class="container">

    <form class="j-form form-horizontal">
        <div class="modal" style="display: block; ">
            <div class="modal-header">
                <h3>Войти</h3>
            </div>

            <div class="modal-body">
                <fieldset>
                    <div class="j-email-name control-group">
                        <label class="control-label" for="singup_email">
                            Email:
                        </label>
                        <div class="controls">
                            <div class="input">
                                <input name="email" id="singup_email" type="text" />
                            </div>
                            <p class="j-message help-block">
                                Адрес, который вы указали при регистрации.
                            </p>
                        </div>
                    </div>

                    <div class="j-password-input control-group">
                        <label class="control-label" for="singup_password">Пароль:</label>
                        <div class="controls">
                            <input name="password" id="singup_password" type="password" />
                            <p class="j-message help-block">
                                Пароль который вы указали при регистрации.
                            </p>
                        </div>
                    </div>
                </fieldset>
            </div>

            <div class="modal-footer">
                <a class="btn btn-primary">Войти</a>
                <a class="btn">Забыли пароль?</a>
            </div>
        </div>
        <div class="modal-backdrop"></div>
    </form>

</div>