<!DOCTYPE html>
<html xmlns:tuna>
    <head>
        <?php $this->render('head') ?>
    </head>
    <body>

        <?php $this->render('body') ?>

        <?php $this->render('popups') ?>

        <div class="hide">
            <?php $this->render('templates') ?>
        </div>

        <iframe id="support_frame" name="support_frame" class="hide"
                width="0" height="0" frameborder="0"></iframe>

        <?php $this->render('scripts') ?>
    </body>
</html>